force-app/main/default/objects/Lightning_Carousel_Image__c/Lightning_Carousel_Image__c.object-meta.xml
<CustomObject>
    <label>Lightning Carousel Image</label>
    <nameField>
        <label>Image Filename</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lightning Carousel Images</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lightning_Carousel_Image__c/fields/Image_Description__c.field-meta.xml
<CustomField>
    <fullName>Image_Description__c</fullName>
    <label>Image Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lightning_Carousel_Image__c/fields/Image_Heading__c.field-meta.xml
<CustomField>
    <fullName>Image_Heading__c</fullName>
    <label>Image Heading</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lightning_Carousel_Image__c/fields/Image_Link__c.field-meta.xml
<CustomField>
    <fullName>Image_Link__c</fullName>
    <label>Image Link</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/LightningCarouselController.cls
public class LightningCarouselController {
    
    @AuraEnabled
    public static List<Lightning_Carousel_Image__c> getCarouselImages(Integer numberToRetrieve) {

        List<Lightning_Carousel_Image__c> carouselItems = new List<Lightning_Carousel_Image__c>(
        	[SELECT Name, Image_URL__c, Image_Heading__c, Image_Description__c, Image_Link__c 
             FROM Lightning_Carousel_Image__c 
             ORDER BY Name DESC
             LIMIT :numberToRetrieve]
        );
        
        return carouselItems;
        
    }

}